apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: "e2e-${APPLICATION}-${ENVIRONMENT}"
namePrefix: server-
labels:
  - pairs:
      app.kubernetes.io/name: "${APPLICATION}"
      app.kubernetes.io/instance: "${ENVIRONMENT}"
      app.kubernetes.io/component: server
    fields:
      - group: ""
        version: v1
        kind: Service
        path: spec/selector
        create: true
      - group: apps
        version: v1
        kind: Deployment
        path: spec/selector/matchLabels
        create: true
      - group: apps
        version: v1
        kind: Deployment
        path: spec/template/metadata/labels
        create: true
  - pairs:
      app.kubernetes.io/version: "${COMMIT_SHA}"
    fields:
      - group: apps
        version: v1
        kind: Deployment
        path: spec/template/metadata/labels
        create: true
resources:
  - workload.yaml
